// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/contract/inbound.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	contract "github.com/mateusmacedo/govibranium/prototype/internal/application/contract"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockSource) Open() (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockSourceMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSource)(nil).Open))
}

// MockSourceReader is a mock of SourceReader interface.
type MockSourceReader struct {
	ctrl     *gomock.Controller
	recorder *MockSourceReaderMockRecorder
}

// MockSourceReaderMockRecorder is the mock recorder for MockSourceReader.
type MockSourceReaderMockRecorder struct {
	mock *MockSourceReader
}

// NewMockSourceReader creates a new mock instance.
func NewMockSourceReader(ctrl *gomock.Controller) *MockSourceReader {
	mock := &MockSourceReader{ctrl: ctrl}
	mock.recorder = &MockSourceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceReader) EXPECT() *MockSourceReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockSourceReader) Read(s contract.Source) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", s)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockSourceReaderMockRecorder) Read(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockSourceReader)(nil).Read), s)
}
